name: flutter_crush
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ^3.1.0
  flutter: ^3.13.0
  # sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  quiver:
  # rxdart: ^0.19.0
  rxdart: any 
  # audioplayers: ^0.7.8
  # audioplayers: any 
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  logging: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.3.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/background/
    - assets/images/borders/
    - assets/images/tiles/
    - assets/images/deco/
    - assets/images/bombs/
    - assets/audio/

#=========================================================
#=================== flutter gen =========================
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  assets:
    enabled: true

    outputs:
      class_name: MyAssets
      package_parameter_enabled: false
      # Assets.imagesChip
      # style: camel-case

      # Assets.images_chip
      # style: snake-case

      # Assets.images.chip (default style)
      style: dot-delimiter

    exclude:
      - assets/images/chip3/chip3.jpg
      - pictures/chip5.jpg
      - assets/flare/
