name: flutter_crush
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ^3.0.0
  flutter: ^3.10.0
  # sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  quiver:
  # rxdart: ^0.19.0
  rxdart: any 
  # audioplayers: ^0.7.8
  # audioplayers: any 
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/background/
    - assets/images/borders/
    - assets/images/tiles/
    - assets/images/deco/
    - assets/images/bombs/
    - assets/audio/
